package moe.ninevolt.kfxgui.exporter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import moe.ninevolt.kfxgui.KfxGui;
import moe.ninevolt.kfxgui.template.Swatch;
import moe.ninevolt.kfxgui.template.TemplateItem;

public class ExportWrap {
    
    private String header;
    private String projectName;
    private String creationDate;
    private String targetTemplater;
    private List<Swatch> swatches;
    private List<ExportItem> lines;

    public ExportWrap(List<TemplateItem> linesIn) {
        this.header = "This file was generated by " +
                        KfxGui.APPLICATION_NAME + " version " + 
                        KfxGui.APPLICATION_VERS + ".";
        this.projectName = KfxGui.getCurrentProject().getName();
        this.creationDate = LocalDateTime.now().toString();
        this.targetTemplater = KfxGui.getCurrentProject().getTargetTemplater();
        this.swatches = Swatch.swatches;
        this.lines = new ArrayList<>();

        for (TemplateItem line : linesIn) {
            this.lines.add(new ExportItem(line));
        }
    }

    public String getHeader() {
        return this.header;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public String getCreationDate() {
        return this.creationDate;
    }

    public String getTargetTemplater() {
        return this.targetTemplater;
    }

    public List<Swatch> getSwatches() {
        return this.swatches;
    }

    public List<ExportItem> getLines() {
        return this.lines;
    }

}
